apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: nats
          image: {{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 4222
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"  
        
         