apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-node-port
  labels:
    app: nats
spec:
  type: NodePort
  ports:
    - port: 4222
      targetPort: 4222
      nodePort: 32225
  selector:
    app: nats
