apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          securityContext:
            runAsUser: 1001
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"  
          env:
            - name: MONGODB_DISABLE_ENFORCE_AUTH
              value: "true"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.database }}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mongodb  
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc