apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-node-port
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32018
  selector:
    app: mongodb