apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName: {{ include "backend-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.namespace }}/{{ index .Values .Release.Name "image" "repository" | default .Values.image.repository | default .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- $globalEnv := .Values.global.backendService.env }}
            {{- $localEnv := .Values.env | default list }}
            {{- $mergedEnv := list }}
            {{- range $globalEnv }}
            {{- $name := .name }}
            {{- $value := .value }}
            {{- range $localEnv }}
            {{- if eq .name $name }}
            {{- $value = .value }}
            {{- end }}
            {{- end }}
            {{- $mergedEnv = append $mergedEnv (dict "name" $name "value" $value) }}
            {{- end }}
            {{- range $localEnv }}
            {{- if not (has .name (pluck "name" $globalEnv)) }}
            {{- $mergedEnv = append $mergedEnv . }}
            {{- end }}
            {{- end }}
            {{- toYaml $mergedEnv | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
