replicaCount: 1

image:
  repository: nginx/nginx-ingress
  tag: "3.1.1"

service:
  type: LoadBalancer

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: 10.86.62.31
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

config:
  enableSnippets: true
