apiVersion: v1
kind: ConfigMap
metadata:
  name: ehiring-backend-router-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 3000;
        
        location /api/competencies {
          proxy_pass http://ehiring-competencies-backend-service:3000;
        }
        
        location /api/competency-groups {
          proxy_pass http://ehiring-competencies-backend-service:3000;
        }
        
        location /api/dashboard {
          proxy_pass http://ehiring-dashboard-backend-service:3000;
        }
        
        location /api/emails {
          proxy_pass http://ehiring-emails-backend-service:3000;
        }
        
        location /api/file-manager {
          proxy_pass http://ehiring-file-manager-backend-service:3000;
        }
        
        location /api/gpt {
          proxy_pass http://ehiring-gpt-backend-service:3000;
        }
        
        location /api/integrations {
          proxy_pass http://ehiring-integrations-backend-service:3000;
        }
        
        location /api/job-descriptions {
          proxy_pass http://ehiring-job-descriptions-backend-service:3000;
        }
        
        location /api/job-description-groups {
          proxy_pass http://ehiring-job-descriptions-backend-service:3000;
        }
        
        location /api/mail-templates {
          proxy_pass http://ehiring-mail-templates-backend-service:3000;
        }
        
        location /api/masterdata {
          proxy_pass http://ehiring-masterdata-backend-service:3000;
        }
        
        location /api/recruitment-plans {
          proxy_pass http://ehiring-recruitment-backend-service:3000;
        }
        
        location /api/recruitment-requests {
          proxy_pass http://ehiring-recruitment-backend-service:3000;
        }
        
        location /api/applications {
          proxy_pass http://ehiring-recruitment-backend-service:3000;
        }
        
        location /api/offers {
          proxy_pass http://ehiring-recruitment-backend-service:3000;
        }
        
        location /api/schedules {
          proxy_pass http://ehiring-schedules-backend-service:3000;
        }
        
        location /api/schedule-groups {
          proxy_pass http://ehiring-schedules-backend-service:3000;
        }
        
        location /api/evaluation-forms {
          proxy_pass http://ehiring-schedules-backend-service:3000;
        }
        
        location /api/evaluation-form-groups {
          proxy_pass http://ehiring-schedules-backend-service:3000;
        }
        
        location /api/talent-pools {
          proxy_pass http://ehiring-talent-pools-backend-service:3000;
        }
        
        location /api/talents {
          proxy_pass http://ehiring-talent-pools-backend-service:3000;
        }
        
        location /api/resumes {
          proxy_pass http://ehiring-talent-pools-backend-service:3000;
        }
        
        location /api/users {
          proxy_pass http://ehiring-users-backend-service:3000;
        }
        
        location /api/user-groups {
          proxy_pass http://ehiring-users-backend-service:3000;
        }
        
        location /api/websites {
          proxy_pass http://ehiring-websites-backend-service:3000;
        }
        
        location /api {
          proxy_pass http://ehiring-portal-backend-service:3000;
        }
        
        location / {
          return 404;
        }
      }
    }