apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "backend-service.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
    - host:
    - http:
        paths:
        {{- if eq (.Values.ingressType | default "backend") "backend" }}
        {{- if .Values.router.enabled }}
        {{- range .Values.router.routes }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend-service.fullname" $ }}-service
                port: 
                  number: {{ include "ehiring.backend-service.port" . }}
        {{- end }}
        {{- end }}
        {{- end }}