apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ehiring.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.global.host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-ehiring-host-service
          port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ehiring.fullname" . }}-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ehiring.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    {{- range $name, $config := .Values }}
    {{- if and (kindIs "map" $config) (hasKey $config "router") ($config.router.enabled) }}
    {{- range $route := $config.router.routes }}
    - match: Host(`{{ $.Values.global.host }}`) && PathPrefix(`{{ $route.path }}`)
      kind: Rule
      middlewares:
        - name: {{ include "ehiring.fullname" $ }}-strip-prefix
      services:
        - name: {{ $.Release.Name }}-{{ $name }}-service
          port: 3000
    {{- end }}
    {{- end }}
    {{- end }}