apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ehiring-ingress
  annotations:
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      {{- range $key, $value := .Values }}
      {{- if and (hasSuffix "-backend" $key) $value.router.routes }}
      {{- range $value.router.routes }}
      - path: {{ .path }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ $key }}-service
            port: 
              number: 3000
      {{- end }}
      {{- end }}
      {{- end }}
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: ehiring-frontend-service
            port: 
              number: 8080