apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "ehiring.fullname" . }}-backend
spec:
  entryPoints:
    - websecure
  routes:
    {{- range $name, $config := .Values }}
    {{- if and (kindIs "map" $config) (hasKey $config "ingress") (eq $config.ingress.type "backend") }}
    {{- if and (kindIs "map" $config) (hasKey $config "router") ($config.router.enabled) }}
    {{- range $host := default $.Values.global.hosts $config.hosts }}
    {{- range $route := $config.router.routes }}
    - match: Host(`{{ $host }}`) && PathPrefix(`{{ $route.path }}`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-{{ $name }}-service
          port: {{ default 3000 $config.service.port }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.global.ssl.enabled }}
  tls:
    secretName: letsencrypt-prod
  {{- end }}