apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-node-port
  labels:
    app: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      name: minio-ui
      nodePort: 32090
    - port: 9001
      targetPort: 9001
      name: minio
      nodePort: 32091
  selector:
    app: minio