minio:
  image:
    repository: bitnami/minio
    tag: "latest"
  rootPassword: "bitnami-minio"
  rootUsername: "minio"

services:
  - name: minio-service-ui
    type: NodePort
    nodePort: 32091
    port: 9001
    targetPort: 9001
  - name: minio-service
    type: ClusterIP
    port: 9000
    targetPort: 9000
volumes:
  - name: minio-data
    path: /data
    persistence:
      size: 5Gi
      storageClass: local-storage
  - name: minio-bitnami-data
    path: /bitnami/minio/data
    persistence:
      size: 5Gi
      storageClass: local-storage
  