apiVersion: cert-manager.io/v1alpha2
kind: Certificate
  metadata:
    name: certificate-name
spec:
  secretName: tls-cert
  duration: 24h
  renewBefore: 12h
  commonName: hostname
  dnsNames:
  - tanlong.10.86.62.31.sslip.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer